# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ran_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ran_messages.proto\"\x89\x01\n\x13RAN_param_map_entry\x12\x1b\n\x03key\x18\x01 \x02(\x0e\x32\x0e.RAN_parameter\x12\x15\n\x0bint64_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x1d\n\x07ue_list\x18\x04 \x01(\x0b\x32\n.ue_list_mH\x00\x42\x07\n\x05value\"?\n\x16RAN_indication_request\x12%\n\rtarget_params\x18\x01 \x03(\x0e\x32\x0e.RAN_parameter\"B\n\x17RAN_indication_response\x12\'\n\tparam_map\x18\x01 \x03(\x0b\x32\x14.RAN_param_map_entry\"E\n\x13RAN_control_request\x12.\n\x10target_param_map\x18\x01 \x03(\x0b\x32\x14.RAN_param_map_entry\"\xea\x01\n\x0bRAN_message\x12#\n\x08msg_type\x18\x01 \x02(\x0e\x32\x11.RAN_message_type\x12\x39\n\x16ran_indication_request\x18\x02 \x01(\x0b\x32\x17.RAN_indication_requestH\x00\x12;\n\x17ran_indication_response\x18\x03 \x01(\x0b\x32\x18.RAN_indication_responseH\x00\x12\x33\n\x13ran_control_request\x18\x04 \x01(\x0b\x32\x14.RAN_control_requestH\x00\x42\t\n\x07payload\"\x87\x01\n\tue_info_m\x12\x0c\n\x04rnti\x18\x01 \x02(\x05\x12\x13\n\x0bmeas_type_1\x18\x02 \x01(\x02\x12\x13\n\x0bmeas_type_2\x18\x03 \x01(\x02\x12\x13\n\x0bmeas_type_3\x18\x04 \x01(\x02\x12\x1d\n\x06prop_1\x18\x05 \x01(\x0e\x32\r.RAN_mcs_type\x12\x0e\n\x06prop_2\x18\x06 \x01(\x02\"?\n\tue_list_m\x12\x15\n\rconnected_ues\x18\x01 \x02(\x05\x12\x1b\n\x07ue_info\x18\x02 \x03(\x0b\x32\n.ue_info_m*b\n\x10RAN_message_type\x12\x10\n\x0cSUBSCRIPTION\x10\x01\x12\x16\n\x12INDICATION_REQUEST\x10\x02\x12\x17\n\x13INDICATION_RESPONSE\x10\x03\x12\x0b\n\x07\x43ONTROL\x10\x04*(\n\rRAN_parameter\x12\n\n\x06GNB_ID\x10\x01\x12\x0b\n\x07UE_LIST\x10\x03*2\n\x0cRAN_mcs_type\x12\x0f\n\x0bSIXTEEN_QAM\x10\x01\x12\x11\n\rSIXTYFOUR_QAM\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ran_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RAN_MESSAGE_TYPE']._serialized_start=806
  _globals['_RAN_MESSAGE_TYPE']._serialized_end=904
  _globals['_RAN_PARAMETER']._serialized_start=906
  _globals['_RAN_PARAMETER']._serialized_end=946
  _globals['_RAN_MCS_TYPE']._serialized_start=948
  _globals['_RAN_MCS_TYPE']._serialized_end=998
  _globals['_RAN_PARAM_MAP_ENTRY']._serialized_start=23
  _globals['_RAN_PARAM_MAP_ENTRY']._serialized_end=160
  _globals['_RAN_INDICATION_REQUEST']._serialized_start=162
  _globals['_RAN_INDICATION_REQUEST']._serialized_end=225
  _globals['_RAN_INDICATION_RESPONSE']._serialized_start=227
  _globals['_RAN_INDICATION_RESPONSE']._serialized_end=293
  _globals['_RAN_CONTROL_REQUEST']._serialized_start=295
  _globals['_RAN_CONTROL_REQUEST']._serialized_end=364
  _globals['_RAN_MESSAGE']._serialized_start=367
  _globals['_RAN_MESSAGE']._serialized_end=601
  _globals['_UE_INFO_M']._serialized_start=604
  _globals['_UE_INFO_M']._serialized_end=739
  _globals['_UE_LIST_M']._serialized_start=741
  _globals['_UE_LIST_M']._serialized_end=804
# @@protoc_insertion_point(module_scope)
